[package]
name = "llm_actors"
version = "0.0.1"
edition = "2021"

[workspace]

[dependencies]
#steady_state     = { path = "../../../core", features = ["proactor_nuclei", "prometheus_metrics"], default-features = false }

steady_state     = "0.0.23"
structopt        = "0.3.26"
structopt-derive = "0.4.18"
flexi_logger     = "0.29.0"
log              = "0.4.22"
futures          = "0.3.30"


reqwest = { version = "0.12.7", features = ["blocking", "json"] }
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0"
ureq = { version = "2.5", features = ["json", "serde"] }